#!/usr/bin/env bash
#Write a Bash script that creates an RSA key pair with the following conditions.
#Name of the crated private key must be School with 4096 bits and betty as protected passphrase.
ssh-keygen -t rsa -b 4096 -p betty -f school
